version: '3.8'


services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./db:/db

  app:
    command: sh -c "python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8000"
    build:
      context: ./app
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${APP_SECRET_KEY}
      - ALLOWED_HOSTS="*"
    depends_on:
      - db

